//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Review
    {
        public int Review_ID { get; set; }
        public string Class_ID { get; set; }
        public int User_ID { get; set; }
        public int Rating { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
    }
}
