//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_List
    {
        public Class_List()
        {
            this.Maj_Req = new HashSet<Maj_Req>();
            this.User_Classes = new HashSet<User_Classes>();
        }
    
        public int ID { get; set; }
        public string Class_Code { get; set; }
        public string Class_Name { get; set; }
        public string Class_Description { get; set; }
        public Nullable<int> Credits { get; set; }
        public int UNIV_ID { get; set; }
        public string CIP_Code { get; set; }
        public int College_ID { get; set; }
        public Nullable<int> Major_ID { get; set; }
    
        public virtual College College { get; set; }
        public virtual Major Major { get; set; }
        public virtual Majors_Code Majors_Code { get; set; }
        public virtual University University { get; set; }
        public virtual ICollection<Maj_Req> Maj_Req { get; set; }
        public virtual ICollection<User_Classes> User_Classes { get; set; }
    }
}
