//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internship
    {
        public int Internship_ID { get; set; }
        public string Company_Name { get; set; }
        public string Internship_Title { get; set; }
        public string Time_Frame { get; set; }
        public string Pay { get; set; }
        public string Description { get; set; }
        public string Requirements { get; set; }
    }
}
