//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maj_Req
    {
        public int Maj_Req_ID { get; set; }
        public int Degree_ID { get; set; }
        public int Class_ID { get; set; }
    
        public virtual Class_List Class_List { get; set; }
        public virtual Majors_by_University Majors_by_University { get; set; }
    }
}
