//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Majors_Code
    {
        public Majors_Code()
        {
            this.Class_List = new HashSet<Class_List>();
            this.Majors_by_University = new HashSet<Majors_by_University>();
        }
    
        public string CIP_Code { get; set; }
        public string Major_Name { get; set; }
    
        public virtual ICollection<Class_List> Class_List { get; set; }
        public virtual ICollection<Majors_by_University> Majors_by_University { get; set; }
    }
}
