//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Majors_by_University
    {
        public Majors_by_University()
        {
            this.Maj_Req = new HashSet<Maj_Req>();
        }
    
        public int Degree_ID { get; set; }
        public int UNIV_ID { get; set; }
        public string CIP_Code { get; set; }
        public string College_Name { get; set; }
        public Nullable<int> College_ID { get; set; }
        public Nullable<System.Guid> Chart_ID { get; set; }
    
        public virtual College College { get; set; }
        public virtual ICollection<Maj_Req> Maj_Req { get; set; }
        public virtual Major_Flowchart Major_Flowchart { get; set; }
        public virtual Majors_Code Majors_Code { get; set; }
        public virtual University University { get; set; }
    }
}
