//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major_Flowchart
    {
        public Major_Flowchart()
        {
            this.Majors_by_University = new HashSet<Majors_by_University>();
        }
    
        public System.Guid Chart_ID { get; set; }
        public string fileName { get; set; }
        public string contentType { get; set; }
        public byte[] file { get; set; }
    
        public virtual ICollection<Majors_by_University> Majors_by_University { get; set; }
    }
}
