//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class University
    {
        public University()
        {
            this.Class_List = new HashSet<Class_List>();
            this.Colleges = new HashSet<College>();
            this.Majors = new HashSet<Major>();
            this.Majors_by_University = new HashSet<Majors_by_University>();
            this.User_Classes = new HashSet<User_Classes>();
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int UNIV_ID { get; set; }
        public string UNIV_Name { get; set; }
        public string UNIV_Alias { get; set; }
        public string UNIV_Address { get; set; }
        public string UNIV_City { get; set; }
        public string UNIV_State { get; set; }
        public string UNIV_ZIP { get; set; }
        public string UNIV_Phone { get; set; }
        public string UNIV_URL { get; set; }
        public Nullable<int> In_State_Tuition { get; set; }
        public Nullable<int> Out_State_Tuition { get; set; }
        public Nullable<int> Category_ID { get; set; }
        public string Cname { get; set; }
    
        public virtual ICollection<Class_List> Class_List { get; set; }
        public virtual ICollection<College> Colleges { get; set; }
        public virtual ICollection<Major> Majors { get; set; }
        public virtual ICollection<Majors_by_University> Majors_by_University { get; set; }
        public virtual University_Category University_Category { get; set; }
        public virtual ICollection<User_Classes> User_Classes { get; set; }
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
