//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class University_Category
    {
        public University_Category()
        {
            this.Universities = new HashSet<University>();
        }
    
        public int Category_ID { get; set; }
        public string Category_Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<University> Universities { get; set; }
    }
}
