//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Classes
    {
        public int User_Class_ID { get; set; }
        public int Class_ID { get; set; }
        public string Grade { get; set; }
        public Nullable<double> Grade_Points { get; set; }
        public Nullable<int> Review_ID { get; set; }
        public string Status { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Review { get; set; }
        public Nullable<System.DateTime> Posting_Date { get; set; }
        public Nullable<int> UNIV_ID { get; set; }
        public Nullable<int> Major_ID { get; set; }
        public string User_Name { get; set; }
    
        public virtual Class_List Class_List { get; set; }
        public virtual Major Major { get; set; }
        public virtual University University { get; set; }
    }
}
