//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int User_ID { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string PW { get; set; }
        public string Gender { get; set; }
        public string Level_of_Education { get; set; }
        public Nullable<int> UNIV_ID { get; set; }
        public Nullable<int> Major_ID { get; set; }
        public string User_Image_path { get; set; }
        public string Goal { get; set; }
        public string UserName { get; set; }
    
        public virtual Major Major { get; set; }
        public virtual University University { get; set; }
    }
}
